[package]
edition = "2021"
authors = ["Daniel Egger <daniel@eggers-club.de>"]
categories = [
    "embedded",
    "no-std",
]
description = "Board support crate for the STM32 Nucleo-F103RB microcontroller board"
documentation = "https://docs.rs/nucleo-f103rb"
keywords = [
    "arm",
    "cortex-m",
    "template",
    "bsp",
]
license = "0BSD"
name = "nucleo-f103rb"
version = "0.3.0"
repository = "https://github.com/therealprof/nucleo-f103rb"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"

[dependencies.stm32f1xx-hal]
features = ["stm32f103", "medium", "rt"]
version = "0.10"

[dev-dependencies]
panic-halt = "0.2"
nb = "1.1"

[profile.dev]
debug = true

[profile.release]
debug = true
lto = true
opt-level = "s"
